-- Community Discovery v4: Node NLP configuration and private write boundary.
-- Only community-owned objects are created or changed. public.tags is read only.
begin;

create table if not exists public.community_blocked_words (
  term text primary key,
  active boolean not null default true,
  language text
);
alter table public.community_blocked_words add column if not exists language text;
alter table public.community_blocked_words enable row level security;
revoke all on public.community_blocked_words from anon, authenticated;

insert into public.community_blocked_words(term, language) values
  ('fuck', 'en'), ('fucking', 'en'), ('shit', 'en'), ('bitch', 'en'),
  ('asshole', 'en'), ('bastard', 'en'), ('pukimak', 'ms'), ('lancau', 'ms'),
  ('bangang', 'ms'), ('bodoh', 'ms'), ('操你妈', 'zh'), ('傻逼', 'zh'),
  ('干你娘', 'zh')
on conflict (term) do update set active = true, language = excluded.language;

create table if not exists public.community_moderation_allowlist (
  term text primary key,
  active boolean not null default true,
  note text
);

create table if not exists public.community_location_aliases (
  canonical_location text not null,
  alias text not null,
  active boolean not null default true,
  primary key (canonical_location, alias)
);

create table if not exists public.community_location_tag_rules (
  id bigint generated by default as identity primary key,
  tag_id bigint not null references public.tags(id) on delete cascade,
  location_pattern text,
  place_type text,
  weight numeric(6,2) not null default 1,
  active boolean not null default true,
  check (num_nonnulls(location_pattern, place_type) = 1)
);

create unique index if not exists community_location_tag_rule_unique
  on public.community_location_tag_rules(
    tag_id,
    coalesce(location_pattern, ''),
    coalesce(place_type, '')
  );

create table if not exists public.community_nlp_settings (
  key text primary key,
  value text not null,
  updated_at timestamptz not null default now()
);

alter table public.community_moderation_allowlist enable row level security;
alter table public.community_location_aliases enable row level security;
alter table public.community_location_tag_rules enable row level security;
alter table public.community_nlp_settings enable row level security;

revoke all on public.community_moderation_allowlist from anon, authenticated;
revoke all on public.community_location_aliases from anon, authenticated;
revoke all on public.community_location_tag_rules from anon, authenticated;
revoke all on public.community_nlp_settings from anon, authenticated;

insert into public.community_moderation_allowlist(term, note) values
  ('scunthorpe', 'Location name used to prevent a common substring false positive.')
on conflict (term) do update set active = true, note = excluded.note;

insert into public.community_location_aliases(canonical_location, alias) values
  ('Kuala Lumpur', 'KL'),
  ('Kuala Lumpur', 'Federal Territory of Kuala Lumpur'),
  ('Petronas Twin Towers', 'KLCC'),
  ('Petronas Twin Towers', 'Twin Towers'),
  ('Kwai Chai Hong', 'Ghost Lane'),
  ('Central Market', 'Pasar Seni')
on conflict do nothing;

insert into public.community_nlp_settings(key, value) values
  ('fallback_tag_name', 'Cultural Experience')
on conflict (key) do update set value = excluded.value, updated_at = now();

-- Location mappings target existing shared tag names. If a tag is absent, that
-- mapping is skipped; no shared tag row is inserted or changed.
insert into public.community_location_tag_rules(tag_id, location_pattern, place_type, weight)
select t.id, mapping.location_pattern, mapping.place_type, mapping.weight
from (values
  ('Heritage', 'Kwai Chai Hong', null, 6.0),
  ('Cultural Experience', 'Kwai Chai Hong', null, 4.0),
  ('Traditional Architecture', 'Kwai Chai Hong', null, 3.0),
  ('Landmark', 'Petronas Twin Towers', null, 6.0),
  ('Landmark', 'KLCC', null, 5.0),
  ('Park', 'KLCC Park', null, 6.0),
  ('Nature', 'KLCC Park', null, 4.0),
  ('Market', 'Central Market', null, 6.0),
  ('Traditional Craft', 'Central Market', null, 4.0),
  ('Restaurant', 'Jalan Alor', null, 6.0),
  ('Local Cuisine', 'Jalan Alor', null, 5.0),
  ('Shopping', 'Bukit Bintang', null, 6.0),
  ('Entertainment', 'Bukit Bintang', null, 4.0),
  ('Museum', null, 'museum', 6.0),
  ('Park', null, 'park', 6.0),
  ('Park', null, 'national_park', 6.0),
  ('Restaurant', null, 'restaurant', 6.0),
  ('Cafe', null, 'cafe', 6.0),
  ('Shopping', null, 'shopping_mall', 6.0),
  ('Market', null, 'market', 6.0),
  ('Landmark', null, 'historical_landmark', 5.0),
  ('Religious Heritage', null, 'hindu_temple', 5.0),
  ('Religious Heritage', null, 'mosque', 5.0),
  ('Religious Heritage', null, 'church', 5.0),
  ('Nature', null, 'natural_feature', 5.0)
) as mapping(tag_name, location_pattern, place_type, weight)
join public.tags t on lower(t.name) = lower(mapping.tag_name)
on conflict do nothing;

create unique index if not exists community_one_post_per_trip
  on public.community_posts(trip_session_id)
  where trip_session_id is not null;

create or replace function public.community_validation_context_v4(
  p_user_id uuid,
  p_trip_session_id uuid default null,
  p_post_id uuid default null
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  selected_trip_id uuid;
  selected_post_id uuid;
  trip_owner uuid;
  trip_status text;
  destination text;
  attraction text;
  post_owner uuid;
  post_is_seed boolean;
  participant boolean;
begin
  if p_user_id is null or num_nonnulls(p_trip_session_id, p_post_id) <> 1 then
    return jsonb_build_object('eligible', false, 'reason', 'Choose one trip or post.');
  end if;

  if p_post_id is not null then
    select p.trip_session_id, p.author_id, p.is_seed
      into selected_trip_id, post_owner, post_is_seed
    from public.community_posts p where p.id = p_post_id;
    if not found then return jsonb_build_object('eligible', false, 'reason', 'Post not found.'); end if;
    if post_is_seed or post_owner is distinct from p_user_id then
      return jsonb_build_object('eligible', false, 'reason', 'Only the author can edit this post.');
    end if;
    selected_post_id := p_post_id;
  else
    selected_trip_id := p_trip_session_id;
    select p.id into selected_post_id
    from public.community_posts p where p.trip_session_id = selected_trip_id;
    if selected_post_id is not null then
      return jsonb_build_object('eligible', false, 'reason', 'This completed trip already has a post.');
    end if;
  end if;

  select s.started_by, s.status, g.destination, g.name,
    exists(select 1 from public.travel_group_trip_participants tp
      where tp.session_id = s.id and tp.user_id = p_user_id)
    into trip_owner, trip_status, destination, attraction, participant
  from public.travel_group_trip_sessions s
  join public.travel_groups g on g.id = s.group_id
  where s.id = selected_trip_id;

  if not found then return jsonb_build_object('eligible', false, 'reason', 'Trip session not found.'); end if;
  if trip_status not in ('ended', 'completed') then
    return jsonb_build_object('eligible', false, 'reason', 'Finish the trip before creating a post.');
  end if;
  if trip_owner is distinct from p_user_id and not participant then
    return jsonb_build_object('eligible', false, 'reason', 'You were not a participant in this trip.');
  end if;

  return jsonb_build_object(
    'eligible', true,
    'reason', 'Trip is eligible.',
    'destination', destination,
    'attraction', attraction,
    'trip_session_id', selected_trip_id,
    'existing_post_id', selected_post_id
  );
end;
$$;

create or replace function public.community_create_post_v4(
  p_user_id uuid,
  p_trip_session_id uuid,
  p_title text,
  p_description text,
  p_image_paths text[],
  p_tag_ids bigint[],
  p_moderation_reason text
) returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  new_id uuid;
  path_value text;
  image_index integer;
  context jsonb;
begin
  context := public.community_validation_context_v4(p_user_id, p_trip_session_id, null);
  if not coalesce((context->>'eligible')::boolean, false) then raise exception '%', context->>'reason'; end if;
  if length(trim(p_title)) not between 3 and 120 then raise exception 'Invalid title.'; end if;
  if length(trim(p_description)) not between 10 and 1000 then raise exception 'Invalid description.'; end if;
  if cardinality(p_image_paths) not between 1 and 6 then raise exception 'Select between 1 and 6 pictures.'; end if;
  if cardinality(p_tag_ids) not between 1 and 3 then raise exception 'Automatic tags are missing.'; end if;
  if exists(select 1 from unnest(p_tag_ids) id where not exists(select 1 from public.tags t where t.id = id)) then
    raise exception 'Automatic tag does not exist.';
  end if;
  foreach path_value in array p_image_paths loop
    if path_value is null or path_value not like p_user_id::text || '/%' then
      raise exception 'One or more pictures do not belong to the signed-in user.';
    end if;
  end loop;

  perform set_config('request.jwt.claim.sub', p_user_id::text, true);
  perform set_config('request.jwt.claim.role', 'authenticated', true);
  insert into public.community_posts(
    author_id, author_name, trip_session_id, title, attraction_name,
    location_name, description, image_path, is_seed, moderation_status,
    moderation_reason, location_relevance_score
  ) values (
    p_user_id, public.community_user_display_name(), p_trip_session_id,
    trim(p_title), context->>'attraction', context->>'destination',
    trim(p_description), p_image_paths[1], false, 'approved',
    p_moderation_reason, 100
  ) returning id into new_id;

  insert into public.community_post_tags(post_id, tag_id)
  select new_id, id from unnest(p_tag_ids) id;
  for image_index in 1..cardinality(p_image_paths) loop
    insert into public.community_post_images(post_id, position, image_path)
    values(new_id, image_index - 1, p_image_paths[image_index]);
  end loop;
  return new_id;
end;
$$;

create or replace function public.community_update_post_v4(
  p_user_id uuid,
  p_post_id uuid,
  p_title text,
  p_description text,
  p_image_paths text[],
  p_tag_ids bigint[],
  p_moderation_reason text
) returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  path_value text;
  image_index integer;
  context jsonb;
begin
  context := public.community_validation_context_v4(p_user_id, null, p_post_id);
  if not coalesce((context->>'eligible')::boolean, false) then raise exception '%', context->>'reason'; end if;
  if length(trim(p_title)) not between 3 and 120 then raise exception 'Invalid title.'; end if;
  if length(trim(p_description)) not between 10 and 1000 then raise exception 'Invalid description.'; end if;
  if cardinality(p_image_paths) > 6 then raise exception 'A post can contain up to 6 pictures.'; end if;
  if cardinality(p_tag_ids) not between 1 and 3 then raise exception 'Automatic tags are missing.'; end if;
  if exists(select 1 from unnest(p_tag_ids) id where not exists(select 1 from public.tags t where t.id = id)) then
    raise exception 'Automatic tag does not exist.';
  end if;
  foreach path_value in array p_image_paths loop
    if path_value is null or path_value not like p_user_id::text || '/%' then
      raise exception 'One or more pictures do not belong to the signed-in user.';
    end if;
  end loop;

  perform set_config('request.jwt.claim.sub', p_user_id::text, true);
  perform set_config('request.jwt.claim.role', 'authenticated', true);
  update public.community_posts set
    title = trim(p_title), description = trim(p_description),
    image_path = case when cardinality(p_image_paths) > 0 then p_image_paths[1] else image_path end,
    moderation_status = 'approved', moderation_reason = p_moderation_reason,
    updated_at = now()
  where id = p_post_id;

  delete from public.community_post_tags where post_id = p_post_id;
  insert into public.community_post_tags(post_id, tag_id)
  select p_post_id, id from unnest(p_tag_ids) id;
  if cardinality(p_image_paths) > 0 then
    delete from public.community_post_images where post_id = p_post_id;
    for image_index in 1..cardinality(p_image_paths) loop
      insert into public.community_post_images(post_id, position, image_path)
      values(p_post_id, image_index - 1, p_image_paths[image_index]);
    end loop;
  end if;
  return p_post_id;
end;
$$;

create or replace function public.community_post_id_for_trip_v4(p_trip_session_id uuid)
returns uuid language sql stable security definer set search_path = public
as $$
  select p.id from public.community_posts p
  where p.trip_session_id = p_trip_session_id and p.author_id = auth.uid()
  limit 1;
$$;

revoke all on function public.community_validation_context_v4(uuid,uuid,uuid) from public, anon, authenticated;
revoke all on function public.community_create_post_v4(uuid,uuid,text,text,text[],bigint[],text) from public, anon, authenticated;
revoke all on function public.community_update_post_v4(uuid,uuid,text,text,text[],bigint[],text) from public, anon, authenticated;
grant execute on function public.community_validation_context_v4(uuid,uuid,uuid) to service_role;
grant execute on function public.community_create_post_v4(uuid,uuid,text,text,text[],bigint[],text) to service_role;
grant execute on function public.community_update_post_v4(uuid,uuid,text,text,text[],bigint[],text) to service_role;
grant execute on function public.community_post_id_for_trip_v4(uuid) to authenticated;

revoke execute on function public.create_community_post_v3(uuid,text,text,text[],bigint[]) from public, anon, authenticated;
revoke execute on function public.update_community_post_v3(uuid,text,text,text[],bigint[]) from public, anon, authenticated;

commit;
