-- Community Discovery v3: multi-image galleries and post text moderation.
-- No trip, profile, place, or shared tags table is altered.
begin;

create table if not exists public.community_blocked_words (
  term text primary key,
  active boolean not null default true
);

alter table public.community_blocked_words enable row level security;
revoke all on public.community_blocked_words from anon, authenticated;

insert into public.community_blocked_words(term) values
  ('fuck'), ('fucking'), ('shit'), ('bitch'), ('asshole'), ('bastard'),
  ('pukimak'), ('lancau'), ('bangang'), ('bodoh'),
  ('操你妈'), ('傻逼'), ('干你娘')
on conflict (term) do update set active = true;

create or replace function public.community_contains_blocked_word(input_text text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.community_blocked_words w
    where w.active
      and (
        lower(w.term) = any(
          regexp_split_to_array(lower(coalesce(input_text, '')), '[^[:alnum:]_]+')
        )
        or (
          w.term ~ '[^\x00-\x7F]'
          and position(lower(w.term) in lower(coalesce(input_text, ''))) > 0
        )
      )
  );
$$;

revoke all on function public.community_contains_blocked_word(text) from public;
grant execute on function public.community_contains_blocked_word(text)
  to anon, authenticated;

create table if not exists public.community_post_images (
  id bigint generated by default as identity primary key,
  post_id uuid not null references public.community_posts(id) on delete cascade,
  position smallint not null check (position between 0 and 5),
  image_path text,
  image_url text,
  created_at timestamptz not null default now(),
  unique(post_id, position),
  check (num_nonnulls(image_path, image_url) = 1)
);

alter table public.community_post_images enable row level security;

drop policy if exists community_post_images_read on public.community_post_images;
create policy community_post_images_read on public.community_post_images
for select using (
  exists (
    select 1 from public.community_posts p
    where p.id = post_id and p.moderation_status = 'approved'
  )
);

drop policy if exists community_post_images_owner on public.community_post_images;
create policy community_post_images_owner on public.community_post_images
for all using (
  exists (
    select 1 from public.community_posts p
    where p.id = post_id and p.author_id = auth.uid() and not p.is_seed
  )
) with check (
  exists (
    select 1 from public.community_posts p
    where p.id = post_id and p.author_id = auth.uid() and not p.is_seed
  )
);

insert into public.community_post_images(post_id, position, image_path, image_url)
select id, 0, image_path, image_url
from public.community_posts
where num_nonnulls(image_path, image_url) = 1
on conflict (post_id, position) do update set
  image_path = excluded.image_path,
  image_url = excluded.image_url;

-- Extra correctly matched sample photos for immediate carousel testing.
-- Both additional files are public-domain/CC0 Wikimedia Commons images.
insert into public.community_post_images(post_id, position, image_url) values
  (
    '6f5a3f36-7d79-4d9d-a101-000000000002'::uuid,
    1,
    'https://commons.wikimedia.org/wiki/Special:Redirect/file/Petronas%20Towers%20night%2C%20Kuala%20Lumpur.jpg?width=1200'
  ),
  (
    '6f5a3f36-7d79-4d9d-a101-000000000004'::uuid,
    1,
    'https://commons.wikimedia.org/wiki/Special:Redirect/file/Central%20Market%20in%20Kuala%20Lumpur%202025.jpg?width=1200'
  )
on conflict (post_id, position) do update set
  image_path = excluded.image_path,
  image_url = excluded.image_url;

create or replace function public.community_review_draft(
  post_title text,
  post_description text,
  expected_destination text,
  expected_attraction text
) returns jsonb
language plpgsql
stable
security invoker
set search_path = public
as $$
declare
  combined_text text := lower(concat_ws(' ', post_title, post_description));
  destination_text text := lower(trim(coalesce(expected_destination, '')));
  attraction_text text := lower(trim(coalesce(expected_attraction, '')));
begin
  if length(trim(coalesce(post_title, ''))) < 3 then
    return jsonb_build_object(
      'approved', false,
      'reason', 'Title must contain at least 3 characters.'
    );
  end if;
  if length(trim(coalesce(post_description, ''))) < 10 then
    return jsonb_build_object(
      'approved', false,
      'reason', 'Description must contain at least 10 characters.'
    );
  end if;
  if public.community_contains_blocked_word(
    concat_ws(' ', post_title, post_description)
  ) then
    return jsonb_build_object(
      'approved', false,
      'reason', 'Your post contains inappropriate language. Remove it and try again.'
    );
  end if;
  if attraction_text <> '' and combined_text like '%' || attraction_text || '%' then
    return jsonb_build_object(
      'approved', true,
      'reason', 'Approved: the post matches the completed trip attraction.'
    );
  end if;
  if destination_text <> '' and combined_text like '%' || destination_text || '%' then
    return jsonb_build_object(
      'approved', true,
      'reason', 'Approved: the post matches the completed trip destination.'
    );
  end if;
  if public.community_text_matches_trip(
    post_title, post_description, expected_destination, expected_attraction
  ) then
    return jsonb_build_object(
      'approved', true,
      'reason', 'Approved: a destination keyword matches the completed trip.'
    );
  end if;
  return jsonb_build_object(
    'approved', false,
    'reason', 'The content does not match the completed trip location.'
  );
end;
$$;

create or replace function public.create_community_post_v3(
  p_trip_session_id uuid,
  p_title text,
  p_description text,
  p_image_paths text[],
  p_tag_ids bigint[]
) returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  new_id uuid;
  image_path_value text;
  image_index integer;
begin
  if auth.uid() is null then raise exception 'Please sign in.'; end if;
  if cardinality(p_image_paths) not between 1 and 6 then
    raise exception 'Select between 1 and 6 pictures.';
  end if;
  if public.community_contains_blocked_word(concat_ws(' ', p_title, p_description)) then
    raise exception 'Your post contains inappropriate language. Remove it and try again.';
  end if;
  foreach image_path_value in array p_image_paths loop
    if image_path_value is null
       or image_path_value not like auth.uid()::text || '/%' then
      raise exception 'One or more pictures do not belong to the signed-in user.';
    end if;
  end loop;

  new_id := public.create_community_post_v2(
    p_trip_session_id, p_title, p_description, p_image_paths[1], p_tag_ids
  );

  for image_index in 1..cardinality(p_image_paths) loop
    insert into public.community_post_images(post_id, position, image_path)
    values (new_id, image_index - 1, p_image_paths[image_index]);
  end loop;
  return new_id;
end;
$$;

create or replace function public.update_community_post_v3(
  p_post_id uuid,
  p_title text,
  p_description text,
  p_image_paths text[],
  p_tag_ids bigint[]
) returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  image_path_value text;
  image_index integer;
begin
  if public.community_contains_blocked_word(concat_ws(' ', p_title, p_description)) then
    raise exception 'Your post contains inappropriate language. Remove it and try again.';
  end if;
  if cardinality(p_image_paths) > 6 then
    raise exception 'A post can contain up to 6 pictures.';
  end if;
  if cardinality(p_image_paths) > 0 then
    foreach image_path_value in array p_image_paths loop
      if image_path_value is null
         or image_path_value not like auth.uid()::text || '/%' then
        raise exception 'One or more pictures do not belong to the signed-in user.';
      end if;
    end loop;
  end if;

  perform public.update_community_post_v2(
    p_post_id,
    p_title,
    p_description,
    case when cardinality(p_image_paths) > 0 then p_image_paths[1] else '' end,
    p_tag_ids
  );

  if cardinality(p_image_paths) > 0 then
    delete from public.community_post_images where post_id = p_post_id;
    for image_index in 1..cardinality(p_image_paths) loop
      insert into public.community_post_images(post_id, position, image_path)
      values (p_post_id, image_index - 1, p_image_paths[image_index]);
    end loop;
  end if;
  return p_post_id;
end;
$$;

create or replace function public.community_feed_v3(
  search_query text default '',
  tag_filters bigint[] default '{}',
  result_limit integer default 50,
  result_offset integer default 0,
  bookmarked_only boolean default false
) returns table (
  id uuid, author_id uuid, author_name text, trip_session_id uuid,
  title text, attraction_name text, location_name text, description text,
  image_path text, image_url text, image_paths text[], image_urls text[],
  tags text[], tag_ids bigint[], created_at timestamptz, updated_at timestamptz,
  like_count bigint, comment_count bigint,
  is_liked boolean, is_bookmarked boolean, is_owner boolean,
  moderation_status text
)
language sql
stable
security definer
set search_path = public
as $$
  select p.id, p.author_id, p.author_name, p.trip_session_id,
    p.title, p.attraction_name, p.location_name, p.description,
    p.image_path, p.image_url,
    coalesce((
      select array_agg(i.image_path order by i.position)
      filter (where i.image_path is not null)
      from public.community_post_images i where i.post_id = p.id
    ), '{}'),
    coalesce((
      select array_agg(i.image_url order by i.position)
      filter (where i.image_url is not null)
      from public.community_post_images i where i.post_id = p.id
    ), '{}'),
    coalesce((select array_agg(t.name order by t.name) from public.community_post_tags pt join public.tags t on t.id=pt.tag_id where pt.post_id=p.id), '{}'),
    coalesce((select array_agg(pt.tag_id order by pt.tag_id) from public.community_post_tags pt where pt.post_id=p.id), '{}'),
    p.created_at, p.updated_at,
    (select count(*) from public.community_post_likes l where l.post_id=p.id),
    (select count(*) from public.community_post_comments c where c.post_id=p.id),
    exists(select 1 from public.community_post_likes l where l.post_id=p.id and l.user_id=auth.uid()),
    exists(select 1 from public.community_post_bookmarks b where b.post_id=p.id and b.user_id=auth.uid()),
    (p.author_id is not null and p.author_id=auth.uid()), p.moderation_status
  from public.community_posts p
  where p.moderation_status='approved'
    and (not bookmarked_only or exists(select 1 from public.community_post_bookmarks b where b.post_id=p.id and b.user_id=auth.uid()))
    and (coalesce(cardinality(tag_filters),0)=0 or exists(select 1 from public.community_post_tags pt where pt.post_id=p.id and pt.tag_id=any(tag_filters)))
    and (trim(search_query)='' or lower(concat_ws(' ',p.title,p.attraction_name,p.location_name,p.description,p.author_name)) like '%'||lower(trim(search_query))||'%'
      or exists(select 1 from public.community_post_tags pt join public.tags t on t.id=pt.tag_id where pt.post_id=p.id and lower(t.name) like '%'||lower(trim(search_query))||'%'))
  order by p.created_at desc
  limit least(greatest(result_limit,1),100)
  offset greatest(result_offset,0);
$$;

grant execute on function public.community_review_draft(text,text,text,text)
  to anon, authenticated;
grant execute on function public.create_community_post_v3(uuid,text,text,text[],bigint[])
  to authenticated;
grant execute on function public.update_community_post_v3(uuid,text,text,text[],bigint[])
  to authenticated;
grant execute on function public.community_feed_v3(text,bigint[],integer,integer,boolean)
  to anon, authenticated;

-- The application uses the v3 entry points. Prevent authenticated clients from
-- bypassing the gallery and blocked-language checks through the older RPCs.
revoke execute on function public.create_community_post_v2(uuid,text,text,text,bigint[])
  from authenticated;
revoke execute on function public.update_community_post_v2(uuid,text,text,text,bigint[])
  from authenticated;

commit;
